### ISSUE TITLE
across() needs to ignore grouping vars

### ISSUE THREAD

**Issue by hadley** [tidyverse/dtplyr#173]
``` r
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

mtcars %>% 
  lazy_dt() %>% 
  group_by(cyl) %>% 
  summarise(across(everything(), mean))
#> Source: local data table [3 x 12]
#> Call:   `_DT1`[, .(mpg = mean(mpg), cyl = mean(cyl), disp = mean(disp), 
#>     hp = mean(hp), drat = mean(drat), wt = mean(wt), qsec = mean(qsec), 
#>     vs = mean(vs), am = mean(am), gear = mean(gear), carb = mean(carb)), 
#>     keyby = .(cyl)]
#> Error: Column name `cyl` must not be duplicated.
```

<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by myoung3** [comment]
https://twitter.com/hadleywickham/status/1355276643338752003

**Comment by myoung3** [comment]
Plus another benefit of using the `lapply(.SD, FUN)` approach is that using the idiomatic data.table approach is good for people learning `data.table` via `dtplyr::show_query`.

**Comment by myoung3** [comment]
Actually, the way this is implemented is probably the best approach since the lapply(.SD) approach doesn't generalize well to an arbitrary number of functions.

This is the closest multiple functions comes to working. This *is* optimized, which is good, but the colnames don't get pasted to function names:
``` r
library(data.table)
mtcarsdt <- as.data.table(mtcars)
mtcarsdt[, c(lapply(.SD,mean),lapply(.SD,sum)), by="cyl",.SDcols=3:5]
#>    cyl     disp        hp     drat   disp   hp  drat
#> 1:   6 183.3143 122.28571 3.585714 1283.2  856 25.10
#> 2:   4 105.1364  82.63636 4.070909 1156.5  909 44.78
#> 3:   8 353.1000 209.21429 3.229286 4943.4 2929 45.21
```
<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This could be fixed by following it up with a complicated setnames statement, but it's not a good solution.

In theory this *should* result in column names mean.disp, etc but that doesn't even work because of how the lapply statements get substituted:

``` r
library(data.table)
mtcarsdt <- as.data.table(mtcars)
mtcarsdt[, c("mean"=lapply(.SD,mean),"sum"=lapply(.SD,sum)), by="cyl",.SDcols=3:5]
#>    cyl     disp        hp     drat   disp   hp  drat
#> 1:   6 183.3143 122.28571 3.585714 1283.2  856 25.10
#> 2:   4 105.1364  82.63636 4.070909 1156.5  909 44.78
#> 3:   8 353.1000 209.21429 3.229286 4943.4 2929 45.21

#how it should work according to base R named concatenation of named lists
c(A=list(a=1:3,b=1:3),B=list(a=1:3,b=1:3))
#> $A.a
#> [1] 1 2 3
#> 
#> $A.b
#> [1] 1 2 3
#> 
#> $B.a
#> [1] 1 2 3
#> 
#> $B.b
#> [1] 1 2 3
```

<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If these rowwise/colwise functions ever get implemented it may be easier to use lapply(..SD)
https://github.com/Rdatatable/data.table/issues/1063

**Comment by hadley** [comment]
Yeah, I think the generality of `across()` will be difficult to simulate using `lapply()` etc.
