### ISSUE TITLE
`pivot_longer()`: Incorrect "id" labels when using `".value"` in `names_to`

### ISSUE THREAD

**Issue by markfairbanks** [tidyverse/dtplyr#228]
``` r
library(dtplyr)
library(dplyr)
library(tidyr)

test_df <- tibble(x_5 = 5, x_6 = 6, y_5 = 5, y_6 = 6)

# Actual
lazy_dt(test_df) %>%
  pivot_longer(everything(), names_to = c(".value", "id"), names_sep = "_") %>%
  collect()
#> # A tibble: 2 x 3
#>   id        x     y
#>   <chr> <dbl> <dbl>
#> 1 1         5     5
#> 2 2         6     6

# Expected
test_df %>%
  pivot_longer(everything(), names_to = c(".value", "id"), names_sep = "_")
#> # A tibble: 2 x 3
#>   id        x     y
#>   <chr> <dbl> <dbl>
#> 1 5         5     5
#> 2 6         6     6
```

The "id" column uses the incorrect labels of "1" and "2" instead of "5" and "6". (Relatively easy to fix).

Note: the "id" column currently generated is essentially a "group id" label generated by data.table.

**Comment by myoung3** [comment]
Thanks for documenting. This is a direct result of a limitation of `data.table::melt`--when melting multiple sets of variables data.table doesn't (currently) attempt to parse ids from the column names.  
```
library(data.table)
  dt <- data.table(x_5 = 5, x_6 = 6, y_5 = 5, y_6 = 6)
  melt(dt, measure.vars = list(c("x_5", "x_6"), c("y_5", "y_6"
  )), variable.name = "id", value.name = c("x", "y"), variable.factor = FALSE)
#>    id x y
#> 1:  1 5 5
#> 2:  2 6 6
  
  melt(dt[, list(x_5,x_6)],
       measure.vars = c("x_5", "x_6"), 
       variable.name = "id", 
       value.name = "x", variable.factor = FALSE)
#>     id x
#> 1: x_5 5
#> 2: x_6 6
```
see https://github.com/Rdatatable/data.table/issues/4047, for example

**Comment by myoung3** [comment]
Note this is true even when using the `patterns()` syntax:

````
library(data.table)
dt <- data.table(x_5 = 5, x_6 = 6, y_5 = 5, y_6 = 6)
melt(dt, measure.vars = patterns("x_", "y_"), variable.name="id",value.name=c("x","y"),variable.factor=FALSE)
#>    id x y
#> 1:  1 5 5
#> 2:  2 6 6
```

**Comment by myoung3** [comment]
I guess I'll add some more thoughts about the design differences. When `measure.vars` is a list, each element is supposed to be the same length and elements are assumed to correspond to each other in order (this is directly related to #229).  As a frequent user of `data.table::melt` in the context of multiple sets of variables, my approach to create variable names is something like this:

```
library(data.table)
dt <- data.table(x_5 = 5, x_6 = 6, y_5 = 5, y_6 = 6)
measure.vars <- list(c("x_5", "x_6"), c("y_5", "y_6"))
out <- melt(dt, measure.vars = measure.vars,
     variable.name = "id", value.name = c("x", "y"), variable.factor = FALSE)
lookup <- data.table(idnew=gsub(".*_","",measure.vars[[1]]))
lookup[, id:=as.character(1L:.N)]
out[lookup, idnew:=idnew, on=c("id")]
```

I think this raises a larger question of which of the following is the goal of `dtplyr`:  
1) To translate only `dplyr` features for which `data.table` has exact feature parity, and errors out otherwise
2) To translate as much of `dplyr` as possible so that any `dplyr` code can be run with a `data.table` backend, even if this means writing some additional lines of query code to replicate what `dplyr` does

If the goal is 2, one option here might to try to create a query similar to the above (except better approximating how `dplyr::reshape_longer` parses variable names depending on the `names_sep` arg, using base R).

**Comment by myoung3** [comment]
The query could even call whatever code dplyr is using to parse variable names into group names (assuming that code is exported and an isolated function).  It might seem a bit silly at first to use dplyr in the data.table query, but it sort of makes sense when trying to replicate the exact behavior of dplyr wrt to variable name parsing.

**Comment by hadley** [comment]
The goal is to carefully skate along a line translating the intent of code, without spending too much time getting caught up in the details. I don't think it's possible to exactly translate every dplyr feature to every backend without spending more time than it's worth. If you switch different backends you are probably going to have to spend a little time tweaking your code, and that's ok.

**Comment by myoung3** [comment]
@hadley I think that's a good perspective. Would it be useful to document code that dtplyr can't translate (and how to work around these situations)? Perhaps in a vignette?

**Comment by hadley** [comment]
I don't think it's particularly useful to document it because it changes over time, and tends to be weirder little edge cases.

**Comment by myoung3** [comment]
Right, I supposed that would be a lot of documentation to maintain. And I suppose these github issues at least provide some documentation!
