### ISSUE TITLE
relocate

### ISSUE THREAD

**Issue by D-Se** [tidyverse/dtplyr#232]
Relocate executes and yields data table directly, without a as.data.table call

```r
library(data.table)
library(dtplyr)

flights_DT <- dtplyr::lazy_dt(nycflights13::flights) %>%
    as.data.table()

flights_DT %>%
    relocate(where(is.character), .before = where(is.numeric))
```

**Comment by myoung3** [comment]
From what I understand, piping `flights_DT` into tidyverse queries won't make use of `dtplyr` functions at all since `flights_DT` is  a data.table and thus will be treated as a data.frame using normal dplyr methods.  If you want to use the speed of `data.table`/`dtplyr` you need to pipe an object of class `dtplyr_step` (i.e., the objects that get created by calling `lazy_dt` on data.tables)

Your code:
```
flights_DT <- dtplyr::lazy_dt(nycflights13::flights) %>%
    as.data.table()
```

is just a complicated way of writing `as.data.table(nycflights13::flights)` and thus your code isn't really using `dtplyr` at all. 

When piping a lazy dt (ie an object of class `dtplyr_step`) to `relocate`, the return is also a lazy dt, as is intended.

``` r
library(data.table)
library(dplyr,warn.conflicts = FALSE)
library(dtplyr)
flights_lazyDT <- dtplyr::lazy_dt(nycflights13::flights)
flights_DT <- flights_lazyDT %>% as.data.table()

out <- flights_lazyDT %>%
  relocate(where(is.character), .before = where(is.numeric)) 

class(flights_DT)
#> [1] "data.table" "data.frame"
class(out)
#> [1] "dtplyr_step_first" "dtplyr_step"
```

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

With that said, it does seem like you're found an issue with `dplyr` and not `dplyr`, since it seems the default behavior should be conversion to tibble but that's not happening with `relocate`:

``` r
library(data.table)
library(dplyr,warn.conflicts = FALSE)
flights_DT <- as.data.table(nycflights13::flights)

out2 <- flights_DT %>%
  relocate(where(is.character), .before = where(is.numeric)) 


out3 <- flights_DT %>% 
  group_by(month) %>%
  summarize(x=mean(dep_delay,na.rm=TRUE))

class(out2)
#> [1] "data.table" "data.frame"
class(out3)
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by markfairbanks** [comment]
@myoung3 As of dtplyr v1.1.0 one of the new features is that the `.data.table` method of functions automatically convert to a lazy data.table. For example with `mutate()`:

``` r
library(dtplyr)
library(data.table)
library(dplyr)

test_dt <- data.table(x = 1:3, y = 1:3)

test_dt %>%
  mutate(double_x = x * 2)
#> Source: local data table [3 x 3]
#> Call:   copy(`_DT1`)[, `:=`(double_x = x * 2)]
#> 
#>       x     y double_x
#>   <int> <int>    <dbl>
#> 1     1     1        2
#> 2     2     2        4
#> 3     3     3        6
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

It looks like `relocate()` doesn't have this implemented (even though it should)

**Comment by myoung3** [comment]
@markfairbanks Very cool! I had missed that. Sorry, @D-Se. My mistake.

And on the second point I was mistaken as well, it seems dplyr's behavior (whether it returns a tibble or a data.frame) actually depends on the function. https://stackoverflow.com/questions/61067989/which-tidyverse-functions-return-tibbles
