### ISSUE TITLE
translation vignette feedback

### ISSUE THREAD

**Issue by franknarf1** [tidyverse/dtplyr#73]
Some thoughts re https://github.com/Rdatatable/data.table/issues/3641#issuecomment-505609967 :

- `filter` is mistaken, I think, since `DT[.(pred1, pred2)]` attempts a join. This could be resolved by translating `filter(pred1, pred2)` to `DT[pred1 & pred2]` (maybe optimized by auto-indexing https://github.com/Rdatatable/data.table/issues/1453) or `DT[pred1][pred2]`
- I think it's the case that grouped filter is generally faster using an alternative to the .SD way, though it is clunky: https://stackoverflow.com/a/16325932 On the other hand, improvements are planned for the .SD way: https://github.com/Rdatatable/data.table/issues/735 
- I did not test, but "mutate() allows to refer to variables that you just created" also applies to summarise(), which may also need a fix (eg `mtcars %>% group_by(cyl) %>% summarise(n = n(), nfrac = n/nrow(.))`)

**Comment by hadley** [comment]
Thanks! 

I've fixed the translation for `filter()` so that it now reduces with `&`. Generate multiple calls `[]` feels risky to me — it will help in the case of multiple indexable expressions, but I suspect might otherwise slow down. For now, I'll leave that optimisation up to data.table.

Yes, I'm pinning my hopes on `.SD` being made faster. (I also asked a similar question at a similar time! https://stackoverflow.com/questions/16573995)

I'm going to leave the `summarise()` for now, since it's relatively uncommon in the wild, and I couldn't figure out how to handle it in dbplyr.

**Comment by hadley** [comment]
Added https://github.com/tidyverse/dtplyr/issues/75 to at least give the same error that dbplyr does for `summarise()` that refers to newly created errors.
